Modal work in progress
VladimirBludov/team-project-filmoteka pull request #10
Opened 2022-01-15 08:55 UTC by Yulia-kom

Сделала модальное окно.
 При нажатии на контейнер с фильмом появляется модальное окно, на крестик всё закрывается.
 
 попозже доделаю чтоб плавно появлялось окно и доделаю стили, всё что не доделала.

2022-01-15 12:31 UTC, VladimirBludov requested changes

2022-01-15 12:31 UTC, VladimirBludov commented on src/js/components/film-description-modal.js
> +document.querySelectorAll('.films__card').forEach(card => {
так делать не нужно, используй делегирование событий, ставь один обработчик на контейнер, а потом проверяй target, if ( e.target.className !== 'movies__item') { return}
ну а ниже уже открывай окно
(movies__item - так называется класс контейнера уже сделанной карточки )

2022-01-15 12:31 UTC, VladimirBludov commented on src/partials/modals/film-description-modal.html
> +<div class="modal-one-film">
по умолчанию сделай окно скрытым, добавь свой класс modal-one-film--hidden

2022-01-15 12:31 UTC, VladimirBludov commented on src/partials/modals/film-description-modal.html
> +      <h5 class="modal-about">ABOUT</h5>
наверное h4 :-)

2022-01-15 12:31 UTC, VladimirBludov commented on src/sass/modals/_film-description-modal.scss
> +    display: none;
скрытие сделай через опасити и визибилити, чтобы анимировать нормально ;-)

2022-01-15 12:31 UTC, VladimirBludov commented on src/sass/modals/_film-description-modal.scss
> +}
добавь пустую строку в конце

2022-01-15 21:50 UTC, Yulia-kom commented
Исправила все замечания и доделала модалку.

2022-01-16 09:33 UTC, VladimirBludov approved these changes, later dismissed

2022-01-16 09:35 UTC, VladimirBludov approved these changes

2022-01-16 09:35 UTC, merged