header for home
VladimirBludov/team-project-filmoteka pull request #2
Opened 2022-01-12 13:04 UTC by Eugen-Ko

2022-01-12 14:21 UTC, VladimirBludov requested changes

2022-01-12 14:21 UTC, VladimirBludov commented on src/partials/sections/header.html
> +      <input class="input header__input" type="text" placeholder="Поиск фильмов" id="js-input" />
svg  оберни в кнопку тип submit

2022-01-12 14:21 UTC, VladimirBludov commented on src/partials/sections/header.html
> +    <div class="input__wrapper page-active" id="js-search">
вместо div используй form

2022-01-12 14:21 UTC, VladimirBludov commented on src/partials/sections/header.html
> +      <p class="input__error" id="js-input-error"></p>
p вынеси из формы

2022-01-12 14:21 UTC, VladimirBludov commented on src/partials/sections/header.html
> +</header>
добавь пустую строку в конце

2022-01-12 14:21 UTC, VladimirBludov commented on src/sass/sections/_header.scss
> +  background-image: linear-gradient(rgba(0, 0, 0, 0.56), rgba(0, 0, 0, 0.56)),
background-image закрой в медиа-запрос для телефона

2022-01-12 14:21 UTC, VladimirBludov commented on src/sass/sections/_header.scss
> +    height: 24px;
размеры пропиши прямо в svg

2022-01-12 14:21 UTC, VladimirBludov commented on src/sass/sections/_header.scss
> +}
добавь пустую строку в конце

2022-01-12 14:21 UTC, VladimirBludov commented on src/sass/sections/_header.scss
> +    padding: 41px 0 97px;
padding: 41px 0 97px; лишний

2022-01-12 14:21 UTC, VladimirBludov commented on src/sass/sections/_header.scss
> +  width: 280px;
width: 100% поставь (для резиновой верстки)

2022-01-12 14:21 UTC, VladimirBludov commented on src/sass/sections/_header.scss
> +  @include respond-to(tablet) {
используй мои миксины, у тебя не захватывает 1023px, а в телефонной версии 767px (ну или свой поправь, я в нём не разобрался :-()

2022-01-12 15:17 UTC, VladimirBludov commented on src/sass/utils/_variables.scss
> -  'text-third': #ffffff,
не удаляй цвета, они еще в других местах используются

2022-01-13 07:35 UTC, Eugen-Ko commented on src/partials/sections/header.html
> +      <input class="input header__input" type="text" placeholder="Поиск фильмов" id="js-input" />
Для чего ?

2022-01-13 07:35 UTC, Eugen-Ko commented on src/partials/sections/header.html
> +    <div class="input__wrapper page-active" id="js-search">
Ок

2022-01-13 07:35 UTC, Eugen-Ko commented on src/partials/sections/header.html
> +      <p class="input__error" id="js-input-error"></p>
Ок

2022-01-13 07:35 UTC, Eugen-Ko commented on src/partials/sections/header.html
> +</header>
Ок

2022-01-13 07:38 UTC, Eugen-Ko commented on src/sass/sections/_header.scss
> +  background-image: linear-gradient(rgba(0, 0, 0, 0.56), rgba(0, 0, 0, 0.56)),
Так верстка от телефона.  И этот бэкграунд визуально до 768пх.

2022-01-13 07:41 UTC, Eugen-Ko commented on src/sass/sections/_header.scss
> +    height: 24px;
Ок

2022-01-13 07:41 UTC, Eugen-Ko commented on src/sass/sections/_header.scss
> +}
Ок.

2022-01-13 07:43 UTC, Eugen-Ko commented on src/sass/sections/_header.scss
> +    padding: 41px 0 97px;
Ок.

2022-01-13 07:51 UTC, Eugen-Ko commented on src/sass/sections/_header.scss
> +  width: 280px;
От 320 до 768 ширина 280пх а далее 336 пх. Так как на макете. Если ставить 100%, то тогда нужно вешать эти размеры на форму-обертку. Что как бы не меняет сути.

2022-01-13 07:53 UTC, Eugen-Ko commented on src/sass/utils/_variables.scss
> -  'text-third': #ffffff,
Поставил на место

2022-01-13 08:02 UTC, Eugen-Ko commented on src/sass/sections/_header.scss
> +  @include respond-to(tablet) {
Вот это не понял. У меня перещелкиваются свойства селекторов при переходе с 767 на 768 и 1023 на 1024.
Что не захватывает или какое свойство не срабатывает?

2022-01-13 08:34 UTC, VladimirBludov commented on src/sass/sections/_header.scss
> +  background-image: linear-gradient(rgba(0, 0, 0, 0.56), rgba(0, 0, 0, 0.56)),
чтобы не перезаписывался, это правило хорошого кода

2022-01-13 08:37 UTC, VladimirBludov commented on src/sass/sections/_header.scss
> +  width: 280px;
на инпут просто ставь 100% (это будет действовать, при меньше 320), а уже в медиа закрывай, как ты написал

2022-01-13 08:37 UTC, VladimirBludov commented on src/sass/sections/_header.scss
> +  @include respond-to(tablet) {
это уже поправил

2022-01-13 08:41 UTC, VladimirBludov requested changes

2022-01-13 08:41 UTC, VladimirBludov commented on src/partials/sections/header.html
> +      <input class="input header__input" type="text" placeholder="Поиск фильмов" id="js-input" />
потому, что это будет кнопка поиска, на которую будут нажимать, и будет происходить поиск по ключевому слову и рендер карточек по результату

2022-01-13 09:05 UTC, Eugen-Ko commented on src/partials/sections/header.html
> +      <input class="input header__input" type="text" placeholder="Поиск фильмов" id="js-input" />
Ок.

2022-01-13 09:06 UTC, Eugen-Ko commented on src/sass/sections/_header.scss
> +  background-image: linear-gradient(rgba(0, 0, 0, 0.56), rgba(0, 0, 0, 0.56)),
Ок

2022-01-13 09:21 UTC, Eugen-Ko commented on src/sass/sections/_header.scss
> +  width: 280px;
ок

2022-01-13 09:23 UTC, Eugen-Ko commented
При размере менше 320 не определены паддинги контейнера и элементы липнут к бокам.

2022-01-13 09:36 UTC, VladimirBludov approved these changes

2022-01-13 09:37 UTC, merged