footer
VladimirBludov/team-project-filmoteka pull request #7
Opened 2022-01-14 09:32 UTC by forysiak-vova

2022-01-14 10:04 UTC, VladimirBludov requested changes

2022-01-14 10:04 UTC, VladimirBludov commented on src/images/seruce.svg
> +<svg width="14" height="13" viewBox="0 0 14 13" fill="none" xmlns="http://www.w3.org/2000/svg">
svg добавь в уже существующий спрайт и используй от туда, этот файл удали.

2022-01-14 10:04 UTC, VladimirBludov commented on src/partials/sections/footer.html
> +
p class="footer__rights"> © 2020 | All Rights Reserved | </p не нужно оборачивать в div

2022-01-14 20:21 UTC, forysiak-vova commented on src/images/seruce.svg
> +<svg width="14" height="13" viewBox="0 0 14 13" fill="none" xmlns="http://www.w3.org/2000/svg">
виправив

2022-01-14 20:21 UTC, forysiak-vova commented on src/partials/sections/footer.html
> +
виправив

2022-01-15 08:14 UTC, VladimirBludov approved these changes

2022-01-15 08:14 UTC, merged